// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/le0x/v1/agent_control.proto

package le0xv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Versions are independent. IDs are opaque strings, validated at the domain boundary.
type AgentHello struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion       uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SchemaVersion         uint32                 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	AgentId               string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId                string                 `protobuf:"bytes,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname              string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	EnrollmentToken       string                 `protobuf:"bytes,6,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"`
	CertificateRequestDer []byte                 `protobuf:"bytes,7,opt,name=certificate_request_der,json=certificateRequestDer,proto3" json:"certificate_request_der,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{0}
}

func (x *AgentHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AgentHello) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *AgentHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHello) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AgentHello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentHello) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *AgentHello) GetCertificateRequestDer() []byte {
	if x != nil {
		return x.CertificateRequestDer
	}
	return nil
}

type ControllerHello struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion      uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SchemaVersion        uint32                 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ControllerId         string                 `protobuf:"bytes,3,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	FarmId               string                 `protobuf:"bytes,4,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	AgentCertificateDer  []byte                 `protobuf:"bytes,5,opt,name=agent_certificate_der,json=agentCertificateDer,proto3" json:"agent_certificate_der,omitempty"`
	FarmCaCertificateDer []byte                 `protobuf:"bytes,6,opt,name=farm_ca_certificate_der,json=farmCaCertificateDer,proto3" json:"farm_ca_certificate_der,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ControllerHello) Reset() {
	*x = ControllerHello{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerHello) ProtoMessage() {}

func (x *ControllerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerHello.ProtoReflect.Descriptor instead.
func (*ControllerHello) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControllerHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ControllerHello) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ControllerHello) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *ControllerHello) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

func (x *ControllerHello) GetAgentCertificateDer() []byte {
	if x != nil {
		return x.AgentCertificateDer
	}
	return nil
}

func (x *ControllerHello) GetFarmCaCertificateDer() []byte {
	if x != nil {
		return x.FarmCaCertificateDer
	}
	return nil
}

type Heartbeat struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Timestamp             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ObservedStateRevision uint64                 `protobuf:"varint,2,opt,name=observed_state_revision,json=observedStateRevision,proto3" json:"observed_state_revision,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Heartbeat) GetObservedStateRevision() uint64 {
	if x != nil {
		return x.ObservedStateRevision
	}
	return 0
}

// Pong echoes the nonce byte-for-byte; it is not an authentication mechanism.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{3}
}

func (x *Ping) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{4}
}

func (x *Pong) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type GetStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatus) Reset() {
	*x = GetStatus{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatus) ProtoMessage() {}

func (x *GetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatus.ProtoReflect.Descriptor instead.
func (*GetStatus) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{5}
}

type GetInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventory) Reset() {
	*x = GetInventory{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventory) ProtoMessage() {}

func (x *GetInventory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventory.ProtoReflect.Descriptor instead.
func (*GetInventory) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{6}
}

type ExecutionPlan struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId      string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Executable       string                 `protobuf:"bytes,2,opt,name=executable,proto3" json:"executable,omitempty"`
	Args             []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Environment      map[string]string      `protobuf:"bytes,4,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDirectory string                 `protobuf:"bytes,5,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	RestartPolicy    string                 `protobuf:"bytes,6,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionPlan) Reset() {
	*x = ExecutionPlan{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPlan) ProtoMessage() {}

func (x *ExecutionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPlan.ProtoReflect.Descriptor instead.
func (*ExecutionPlan) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionPlan) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionPlan) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *ExecutionPlan) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecutionPlan) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ExecutionPlan) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *ExecutionPlan) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

type StartExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *ExecutionPlan         `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartExecution) Reset() {
	*x = StartExecution{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartExecution) ProtoMessage() {}

func (x *StartExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartExecution.ProtoReflect.Descriptor instead.
func (*StartExecution) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{8}
}

func (x *StartExecution) GetPlan() *ExecutionPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type StopExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopExecution) Reset() {
	*x = StopExecution{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopExecution) ProtoMessage() {}

func (x *StopExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopExecution.ProtoReflect.Descriptor instead.
func (*StopExecution) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{9}
}

func (x *StopExecution) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type RestartExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartExecution) Reset() {
	*x = RestartExecution{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartExecution) ProtoMessage() {}

func (x *RestartExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartExecution.ProtoReflect.Descriptor instead.
func (*RestartExecution) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{10}
}

func (x *RestartExecution) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetExecutions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutions) Reset() {
	*x = GetExecutions{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutions) ProtoMessage() {}

func (x *GetExecutions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutions.ProtoReflect.Descriptor instead.
func (*GetExecutions) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{11}
}

type Execution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Pid           int64                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	HasExitCode   bool                   `protobuf:"varint,6,opt,name=has_exit_code,json=hasExitCode,proto3" json:"has_exit_code,omitempty"`
	RestartCount  uint32                 `protobuf:"varint,7,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	LastError     string                 `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Execution) Reset() {
	*x = Execution{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execution) ProtoMessage() {}

func (x *Execution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execution.ProtoReflect.Descriptor instead.
func (*Execution) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{12}
}

func (x *Execution) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Execution) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Execution) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Execution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Execution) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Execution) GetHasExitCode() bool {
	if x != nil {
		return x.HasExitCode
	}
	return false
}

func (x *Execution) GetRestartCount() uint32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *Execution) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ExecutionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *Execution             `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{13}
}

func (x *ExecutionResult) GetExecution() *Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *ExecutionResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Executions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*Execution           `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Executions) Reset() {
	*x = Executions{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Executions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Executions) ProtoMessage() {}

func (x *Executions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Executions.ProtoReflect.Descriptor instead.
func (*Executions) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{14}
}

func (x *Executions) GetExecutions() []*Execution {
	if x != nil {
		return x.Executions
	}
	return nil
}

// The agent state vocabulary is not yet defined in M0.2.
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentState    string                 `protobuf:"bytes,1,opt,name=agent_state,json=agentState,proto3" json:"agent_state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{15}
}

func (x *Status) GetAgentState() string {
	if x != nil {
		return x.AgentState
	}
	return ""
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Physical facts only. This is deliberately a subset of domain Inventory.
type Inventory struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HostId           string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname         string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsId             string                 `protobuf:"bytes,3,opt,name=os_id,json=osId,proto3" json:"os_id,omitempty"`
	OsVersion        string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Architecture     string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	CpuVendor        string                 `protobuf:"bytes,6,opt,name=cpu_vendor,json=cpuVendor,proto3" json:"cpu_vendor,omitempty"`
	CpuModel         string                 `protobuf:"bytes,7,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuCores         uint32                 `protobuf:"varint,8,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuThreads       uint32                 `protobuf:"varint,9,opt,name=cpu_threads,json=cpuThreads,proto3" json:"cpu_threads,omitempty"`
	Gpus             []*GPU                 `protobuf:"bytes,10,rep,name=gpus,proto3" json:"gpus,omitempty"`
	MemoryTotalBytes uint64                 `protobuf:"varint,11,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{16}
}

func (x *Inventory) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Inventory) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Inventory) GetOsId() string {
	if x != nil {
		return x.OsId
	}
	return ""
}

func (x *Inventory) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Inventory) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Inventory) GetCpuVendor() string {
	if x != nil {
		return x.CpuVendor
	}
	return ""
}

func (x *Inventory) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *Inventory) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Inventory) GetCpuThreads() uint32 {
	if x != nil {
		return x.CpuThreads
	}
	return 0
}

func (x *Inventory) GetGpus() []*GPU {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *Inventory) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

type GPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	PciBusId      string                 `protobuf:"bytes,4,opt,name=pci_bus_id,json=pciBusId,proto3" json:"pci_bus_id,omitempty"`
	Uuid          string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"` // Empty when unavailable.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPU) Reset() {
	*x = GPU{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU) ProtoMessage() {}

func (x *GPU) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU.ProtoReflect.Descriptor instead.
func (*GPU) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{17}
}

func (x *GPU) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GPU) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPU) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPU) GetPciBusId() string {
	if x != nil {
		return x.PciBusId
	}
	return ""
}

func (x *GPU) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type TypedError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // Canonical internal/farmerr code, not a human message.
	HumanMessage  string                 `protobuf:"bytes,2,opt,name=human_message,json=humanMessage,proto3" json:"human_message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SuggestedFix  string                 `protobuf:"bytes,4,opt,name=suggested_fix,json=suggestedFix,proto3" json:"suggested_fix,omitempty"`
	LogsRef       string                 `protobuf:"bytes,5,opt,name=logs_ref,json=logsRef,proto3" json:"logs_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedError) Reset() {
	*x = TypedError{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedError) ProtoMessage() {}

func (x *TypedError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedError.ProtoReflect.Descriptor instead.
func (*TypedError) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{18}
}

func (x *TypedError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TypedError) GetHumanMessage() string {
	if x != nil {
		return x.HumanMessage
	}
	return ""
}

func (x *TypedError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *TypedError) GetSuggestedFix() string {
	if x != nil {
		return x.SuggestedFix
	}
	return ""
}

func (x *TypedError) GetLogsRef() string {
	if x != nil {
		return x.LogsRef
	}
	return ""
}

type CommandEnvelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // Opaque correlation ID, echoed in CommandResult.
	// Types that are valid to be assigned to Command:
	//
	//	*CommandEnvelope_Ping
	//	*CommandEnvelope_GetStatus
	//	*CommandEnvelope_GetInventory
	//	*CommandEnvelope_StartExecution
	//	*CommandEnvelope_StopExecution
	//	*CommandEnvelope_RestartExecution
	//	*CommandEnvelope_GetExecutions
	Command       isCommandEnvelope_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandEnvelope) Reset() {
	*x = CommandEnvelope{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEnvelope) ProtoMessage() {}

func (x *CommandEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEnvelope.ProtoReflect.Descriptor instead.
func (*CommandEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{19}
}

func (x *CommandEnvelope) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandEnvelope) GetCommand() isCommandEnvelope_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandEnvelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *CommandEnvelope) GetGetStatus() *GetStatus {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_GetStatus); ok {
			return x.GetStatus
		}
	}
	return nil
}

func (x *CommandEnvelope) GetGetInventory() *GetInventory {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_GetInventory); ok {
			return x.GetInventory
		}
	}
	return nil
}

func (x *CommandEnvelope) GetStartExecution() *StartExecution {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_StartExecution); ok {
			return x.StartExecution
		}
	}
	return nil
}

func (x *CommandEnvelope) GetStopExecution() *StopExecution {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_StopExecution); ok {
			return x.StopExecution
		}
	}
	return nil
}

func (x *CommandEnvelope) GetRestartExecution() *RestartExecution {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_RestartExecution); ok {
			return x.RestartExecution
		}
	}
	return nil
}

func (x *CommandEnvelope) GetGetExecutions() *GetExecutions {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_GetExecutions); ok {
			return x.GetExecutions
		}
	}
	return nil
}

type isCommandEnvelope_Command interface {
	isCommandEnvelope_Command()
}

type CommandEnvelope_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type CommandEnvelope_GetStatus struct {
	GetStatus *GetStatus `protobuf:"bytes,3,opt,name=get_status,json=getStatus,proto3,oneof"`
}

type CommandEnvelope_GetInventory struct {
	GetInventory *GetInventory `protobuf:"bytes,4,opt,name=get_inventory,json=getInventory,proto3,oneof"`
}

type CommandEnvelope_StartExecution struct {
	StartExecution *StartExecution `protobuf:"bytes,5,opt,name=start_execution,json=startExecution,proto3,oneof"`
}

type CommandEnvelope_StopExecution struct {
	StopExecution *StopExecution `protobuf:"bytes,6,opt,name=stop_execution,json=stopExecution,proto3,oneof"`
}

type CommandEnvelope_RestartExecution struct {
	RestartExecution *RestartExecution `protobuf:"bytes,7,opt,name=restart_execution,json=restartExecution,proto3,oneof"`
}

type CommandEnvelope_GetExecutions struct {
	GetExecutions *GetExecutions `protobuf:"bytes,8,opt,name=get_executions,json=getExecutions,proto3,oneof"`
}

func (*CommandEnvelope_Ping) isCommandEnvelope_Command() {}

func (*CommandEnvelope_GetStatus) isCommandEnvelope_Command() {}

func (*CommandEnvelope_GetInventory) isCommandEnvelope_Command() {}

func (*CommandEnvelope_StartExecution) isCommandEnvelope_Command() {}

func (*CommandEnvelope_StopExecution) isCommandEnvelope_Command() {}

func (*CommandEnvelope_RestartExecution) isCommandEnvelope_Command() {}

func (*CommandEnvelope_GetExecutions) isCommandEnvelope_Command() {}

type CommandResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*CommandResult_Pong
	//	*CommandResult_Status
	//	*CommandResult_Inventory
	//	*CommandResult_Error
	//	*CommandResult_Execution
	//	*CommandResult_Executions
	Result        isCommandResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{20}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetResult() isCommandResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandResult) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *CommandResult) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *CommandResult) GetInventory() *Inventory {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_Inventory); ok {
			return x.Inventory
		}
	}
	return nil
}

func (x *CommandResult) GetError() *TypedError {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *CommandResult) GetExecution() *ExecutionResult {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_Execution); ok {
			return x.Execution
		}
	}
	return nil
}

func (x *CommandResult) GetExecutions() *Executions {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_Executions); ok {
			return x.Executions
		}
	}
	return nil
}

type isCommandResult_Result interface {
	isCommandResult_Result()
}

type CommandResult_Pong struct {
	Pong *Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type CommandResult_Status struct {
	Status *Status `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type CommandResult_Inventory struct {
	Inventory *Inventory `protobuf:"bytes,4,opt,name=inventory,proto3,oneof"`
}

type CommandResult_Error struct {
	Error *TypedError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type CommandResult_Execution struct {
	Execution *ExecutionResult `protobuf:"bytes,6,opt,name=execution,proto3,oneof"`
}

type CommandResult_Executions struct {
	Executions *Executions `protobuf:"bytes,7,opt,name=executions,proto3,oneof"`
}

func (*CommandResult_Pong) isCommandResult_Result() {}

func (*CommandResult_Status) isCommandResult_Result() {}

func (*CommandResult_Inventory) isCommandResult_Result() {}

func (*CommandResult_Error) isCommandResult_Result() {}

func (*CommandResult_Execution) isCommandResult_Result() {}

func (*CommandResult_Executions) isCommandResult_Result() {}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_CommandResult
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{21}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,3,opt,name=command_result,json=commandResult,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_CommandResult) isAgentMessage_Payload() {}

type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControllerMessage_Hello
	//	*ControllerMessage_Command
	Payload       isControllerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_le0x_v1_agent_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_proto_le0x_v1_agent_control_proto_rawDescGZIP(), []int{22}
}

func (x *ControllerMessage) GetPayload() isControllerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControllerMessage) GetHello() *ControllerHello {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ControllerMessage) GetCommand() *CommandEnvelope {
	if x != nil {
		if x, ok := x.Payload.(*ControllerMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isControllerMessage_Payload interface {
	isControllerMessage_Payload()
}

type ControllerMessage_Hello struct {
	Hello *ControllerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ControllerMessage_Command struct {
	Command *CommandEnvelope `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

func (*ControllerMessage_Hello) isControllerMessage_Payload() {}

func (*ControllerMessage_Command) isControllerMessage_Payload() {}

var File_proto_le0x_v1_agent_control_proto protoreflect.FileDescriptor

const file_proto_le0x_v1_agent_control_proto_rawDesc = "" +
	"\n" +
	"!proto/le0x/v1/agent_control.proto\x12\ale0x.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x02\n" +
	"\n" +
	"AgentHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x04 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12)\n" +
	"\x10enrollment_token\x18\x06 \x01(\tR\x0fenrollmentToken\x126\n" +
	"\x17certificate_request_der\x18\a \x01(\fR\x15certificateRequestDer\"\x8c\x02\n" +
	"\x0fControllerHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersion\x12#\n" +
	"\rcontroller_id\x18\x03 \x01(\tR\fcontrollerId\x12\x17\n" +
	"\afarm_id\x18\x04 \x01(\tR\x06farmId\x122\n" +
	"\x15agent_certificate_der\x18\x05 \x01(\fR\x13agentCertificateDer\x125\n" +
	"\x17farm_ca_certificate_der\x18\x06 \x01(\fR\x14farmCaCertificateDer\"}\n" +
	"\tHeartbeat\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x126\n" +
	"\x17observed_state_revision\x18\x02 \x01(\x04R\x15observedStateRevision\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"\v\n" +
	"\tGetStatus\"\x0e\n" +
	"\fGetInventory\"\xc5\x02\n" +
	"\rExecutionPlan\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1e\n" +
	"\n" +
	"executable\x18\x02 \x01(\tR\n" +
	"executable\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12I\n" +
	"\venvironment\x18\x04 \x03(\v2'.le0x.v1.ExecutionPlan.EnvironmentEntryR\venvironment\x12+\n" +
	"\x11working_directory\x18\x05 \x01(\tR\x10workingDirectory\x12%\n" +
	"\x0erestart_policy\x18\x06 \x01(\tR\rrestartPolicy\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x0eStartExecution\x12*\n" +
	"\x04plan\x18\x01 \x01(\v2\x16.le0x.v1.ExecutionPlanR\x04plan\"2\n" +
	"\rStopExecution\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"5\n" +
	"\x10RestartExecution\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\x0f\n" +
	"\rGetExecutions\"\x96\x02\n" +
	"\tExecution\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x03R\x03pid\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\"\n" +
	"\rhas_exit_code\x18\x06 \x01(\bR\vhasExitCode\x12#\n" +
	"\rrestart_count\x18\a \x01(\rR\frestartCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\"]\n" +
	"\x0fExecutionResult\x120\n" +
	"\texecution\x18\x01 \x01(\v2\x12.le0x.v1.ExecutionR\texecution\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\n" +
	"Executions\x122\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x12.le0x.v1.ExecutionR\n" +
	"executions\"C\n" +
	"\x06Status\x12\x1f\n" +
	"\vagent_state\x18\x01 \x01(\tR\n" +
	"agentState\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe2\x02\n" +
	"\tInventory\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x13\n" +
	"\x05os_id\x18\x03 \x01(\tR\x04osId\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\x12\x1d\n" +
	"\n" +
	"cpu_vendor\x18\x06 \x01(\tR\tcpuVendor\x12\x1b\n" +
	"\tcpu_model\x18\a \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_cores\x18\b \x01(\rR\bcpuCores\x12\x1f\n" +
	"\vcpu_threads\x18\t \x01(\rR\n" +
	"cpuThreads\x12 \n" +
	"\x04gpus\x18\n" +
	" \x03(\v2\f.le0x.v1.GPUR\x04gpus\x12,\n" +
	"\x12memory_total_bytes\x18\v \x01(\x04R\x10memoryTotalBytes\"\x82\x01\n" +
	"\x03GPU\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1c\n" +
	"\n" +
	"pci_bus_id\x18\x04 \x01(\tR\bpciBusId\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\"\xfd\x01\n" +
	"\n" +
	"TypedError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rhuman_message\x18\x02 \x01(\tR\fhumanMessage\x12:\n" +
	"\adetails\x18\x03 \x03(\v2 .le0x.v1.TypedError.DetailsEntryR\adetails\x12#\n" +
	"\rsuggested_fix\x18\x04 \x01(\tR\fsuggestedFix\x12\x19\n" +
	"\blogs_ref\x18\x05 \x01(\tR\alogsRef\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x03\n" +
	"\x0fCommandEnvelope\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12#\n" +
	"\x04ping\x18\x02 \x01(\v2\r.le0x.v1.PingH\x00R\x04ping\x123\n" +
	"\n" +
	"get_status\x18\x03 \x01(\v2\x12.le0x.v1.GetStatusH\x00R\tgetStatus\x12<\n" +
	"\rget_inventory\x18\x04 \x01(\v2\x15.le0x.v1.GetInventoryH\x00R\fgetInventory\x12B\n" +
	"\x0fstart_execution\x18\x05 \x01(\v2\x17.le0x.v1.StartExecutionH\x00R\x0estartExecution\x12?\n" +
	"\x0estop_execution\x18\x06 \x01(\v2\x16.le0x.v1.StopExecutionH\x00R\rstopExecution\x12H\n" +
	"\x11restart_execution\x18\a \x01(\v2\x19.le0x.v1.RestartExecutionH\x00R\x10restartExecution\x12?\n" +
	"\x0eget_executions\x18\b \x01(\v2\x16.le0x.v1.GetExecutionsH\x00R\rgetExecutionsB\t\n" +
	"\acommand\"\xda\x02\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12#\n" +
	"\x04pong\x18\x02 \x01(\v2\r.le0x.v1.PongH\x00R\x04pong\x12)\n" +
	"\x06status\x18\x03 \x01(\v2\x0f.le0x.v1.StatusH\x00R\x06status\x122\n" +
	"\tinventory\x18\x04 \x01(\v2\x12.le0x.v1.InventoryH\x00R\tinventory\x12+\n" +
	"\x05error\x18\x05 \x01(\v2\x13.le0x.v1.TypedErrorH\x00R\x05error\x128\n" +
	"\texecution\x18\x06 \x01(\v2\x18.le0x.v1.ExecutionResultH\x00R\texecution\x125\n" +
	"\n" +
	"executions\x18\a \x01(\v2\x13.le0x.v1.ExecutionsH\x00R\n" +
	"executionsB\b\n" +
	"\x06result\"\xbb\x01\n" +
	"\fAgentMessage\x12+\n" +
	"\x05hello\x18\x01 \x01(\v2\x13.le0x.v1.AgentHelloH\x00R\x05hello\x122\n" +
	"\theartbeat\x18\x02 \x01(\v2\x12.le0x.v1.HeartbeatH\x00R\theartbeat\x12?\n" +
	"\x0ecommand_result\x18\x03 \x01(\v2\x16.le0x.v1.CommandResultH\x00R\rcommandResultB\t\n" +
	"\apayload\"\x86\x01\n" +
	"\x11ControllerMessage\x120\n" +
	"\x05hello\x18\x01 \x01(\v2\x18.le0x.v1.ControllerHelloH\x00R\x05hello\x124\n" +
	"\acommand\x18\x02 \x01(\v2\x18.le0x.v1.CommandEnvelopeH\x00R\acommandB\t\n" +
	"\apayload2P\n" +
	"\fAgentControl\x12@\n" +
	"\aConnect\x12\x15.le0x.v1.AgentMessage\x1a\x1a.le0x.v1.ControllerMessage(\x010\x01B2Z0github.com/le0xdon/le0xfarm/proto/le0x/v1;le0xv1b\x06proto3"

var (
	file_proto_le0x_v1_agent_control_proto_rawDescOnce sync.Once
	file_proto_le0x_v1_agent_control_proto_rawDescData []byte
)

func file_proto_le0x_v1_agent_control_proto_rawDescGZIP() []byte {
	file_proto_le0x_v1_agent_control_proto_rawDescOnce.Do(func() {
		file_proto_le0x_v1_agent_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_le0x_v1_agent_control_proto_rawDesc), len(file_proto_le0x_v1_agent_control_proto_rawDesc)))
	})
	return file_proto_le0x_v1_agent_control_proto_rawDescData
}

var file_proto_le0x_v1_agent_control_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_le0x_v1_agent_control_proto_goTypes = []any{
	(*AgentHello)(nil),            // 0: le0x.v1.AgentHello
	(*ControllerHello)(nil),       // 1: le0x.v1.ControllerHello
	(*Heartbeat)(nil),             // 2: le0x.v1.Heartbeat
	(*Ping)(nil),                  // 3: le0x.v1.Ping
	(*Pong)(nil),                  // 4: le0x.v1.Pong
	(*GetStatus)(nil),             // 5: le0x.v1.GetStatus
	(*GetInventory)(nil),          // 6: le0x.v1.GetInventory
	(*ExecutionPlan)(nil),         // 7: le0x.v1.ExecutionPlan
	(*StartExecution)(nil),        // 8: le0x.v1.StartExecution
	(*StopExecution)(nil),         // 9: le0x.v1.StopExecution
	(*RestartExecution)(nil),      // 10: le0x.v1.RestartExecution
	(*GetExecutions)(nil),         // 11: le0x.v1.GetExecutions
	(*Execution)(nil),             // 12: le0x.v1.Execution
	(*ExecutionResult)(nil),       // 13: le0x.v1.ExecutionResult
	(*Executions)(nil),            // 14: le0x.v1.Executions
	(*Status)(nil),                // 15: le0x.v1.Status
	(*Inventory)(nil),             // 16: le0x.v1.Inventory
	(*GPU)(nil),                   // 17: le0x.v1.GPU
	(*TypedError)(nil),            // 18: le0x.v1.TypedError
	(*CommandEnvelope)(nil),       // 19: le0x.v1.CommandEnvelope
	(*CommandResult)(nil),         // 20: le0x.v1.CommandResult
	(*AgentMessage)(nil),          // 21: le0x.v1.AgentMessage
	(*ControllerMessage)(nil),     // 22: le0x.v1.ControllerMessage
	nil,                           // 23: le0x.v1.ExecutionPlan.EnvironmentEntry
	nil,                           // 24: le0x.v1.TypedError.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
}
var file_proto_le0x_v1_agent_control_proto_depIdxs = []int32{
	25, // 0: le0x.v1.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	23, // 1: le0x.v1.ExecutionPlan.environment:type_name -> le0x.v1.ExecutionPlan.EnvironmentEntry
	7,  // 2: le0x.v1.StartExecution.plan:type_name -> le0x.v1.ExecutionPlan
	25, // 3: le0x.v1.Execution.started_at:type_name -> google.protobuf.Timestamp
	12, // 4: le0x.v1.ExecutionResult.execution:type_name -> le0x.v1.Execution
	12, // 5: le0x.v1.Executions.executions:type_name -> le0x.v1.Execution
	17, // 6: le0x.v1.Inventory.gpus:type_name -> le0x.v1.GPU
	24, // 7: le0x.v1.TypedError.details:type_name -> le0x.v1.TypedError.DetailsEntry
	3,  // 8: le0x.v1.CommandEnvelope.ping:type_name -> le0x.v1.Ping
	5,  // 9: le0x.v1.CommandEnvelope.get_status:type_name -> le0x.v1.GetStatus
	6,  // 10: le0x.v1.CommandEnvelope.get_inventory:type_name -> le0x.v1.GetInventory
	8,  // 11: le0x.v1.CommandEnvelope.start_execution:type_name -> le0x.v1.StartExecution
	9,  // 12: le0x.v1.CommandEnvelope.stop_execution:type_name -> le0x.v1.StopExecution
	10, // 13: le0x.v1.CommandEnvelope.restart_execution:type_name -> le0x.v1.RestartExecution
	11, // 14: le0x.v1.CommandEnvelope.get_executions:type_name -> le0x.v1.GetExecutions
	4,  // 15: le0x.v1.CommandResult.pong:type_name -> le0x.v1.Pong
	15, // 16: le0x.v1.CommandResult.status:type_name -> le0x.v1.Status
	16, // 17: le0x.v1.CommandResult.inventory:type_name -> le0x.v1.Inventory
	18, // 18: le0x.v1.CommandResult.error:type_name -> le0x.v1.TypedError
	13, // 19: le0x.v1.CommandResult.execution:type_name -> le0x.v1.ExecutionResult
	14, // 20: le0x.v1.CommandResult.executions:type_name -> le0x.v1.Executions
	0,  // 21: le0x.v1.AgentMessage.hello:type_name -> le0x.v1.AgentHello
	2,  // 22: le0x.v1.AgentMessage.heartbeat:type_name -> le0x.v1.Heartbeat
	20, // 23: le0x.v1.AgentMessage.command_result:type_name -> le0x.v1.CommandResult
	1,  // 24: le0x.v1.ControllerMessage.hello:type_name -> le0x.v1.ControllerHello
	19, // 25: le0x.v1.ControllerMessage.command:type_name -> le0x.v1.CommandEnvelope
	21, // 26: le0x.v1.AgentControl.Connect:input_type -> le0x.v1.AgentMessage
	22, // 27: le0x.v1.AgentControl.Connect:output_type -> le0x.v1.ControllerMessage
	27, // [27:28] is the sub-list for method output_type
	26, // [26:27] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_le0x_v1_agent_control_proto_init() }
func file_proto_le0x_v1_agent_control_proto_init() {
	if File_proto_le0x_v1_agent_control_proto != nil {
		return
	}
	file_proto_le0x_v1_agent_control_proto_msgTypes[19].OneofWrappers = []any{
		(*CommandEnvelope_Ping)(nil),
		(*CommandEnvelope_GetStatus)(nil),
		(*CommandEnvelope_GetInventory)(nil),
		(*CommandEnvelope_StartExecution)(nil),
		(*CommandEnvelope_StopExecution)(nil),
		(*CommandEnvelope_RestartExecution)(nil),
		(*CommandEnvelope_GetExecutions)(nil),
	}
	file_proto_le0x_v1_agent_control_proto_msgTypes[20].OneofWrappers = []any{
		(*CommandResult_Pong)(nil),
		(*CommandResult_Status)(nil),
		(*CommandResult_Inventory)(nil),
		(*CommandResult_Error)(nil),
		(*CommandResult_Execution)(nil),
		(*CommandResult_Executions)(nil),
	}
	file_proto_le0x_v1_agent_control_proto_msgTypes[21].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_CommandResult)(nil),
	}
	file_proto_le0x_v1_agent_control_proto_msgTypes[22].OneofWrappers = []any{
		(*ControllerMessage_Hello)(nil),
		(*ControllerMessage_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_le0x_v1_agent_control_proto_rawDesc), len(file_proto_le0x_v1_agent_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_le0x_v1_agent_control_proto_goTypes,
		DependencyIndexes: file_proto_le0x_v1_agent_control_proto_depIdxs,
		MessageInfos:      file_proto_le0x_v1_agent_control_proto_msgTypes,
	}.Build()
	File_proto_le0x_v1_agent_control_proto = out.File
	file_proto_le0x_v1_agent_control_proto_goTypes = nil
	file_proto_le0x_v1_agent_control_proto_depIdxs = nil
}
